### ISSUE TITLE
Bug in beam2earth_workhorse.m ?

### ISSUE THREAD

**Issue by andypicke** [OceanMixingGroup/mixingsoftware#1]
I think the line VZS = SSCOR/(2.0_C30) should actually be VZS = SSCOR/(4.0_C30) in beam2earth_workhorse.m . I don't think this affects the horizontal velocities, just the vertical velocities. Found this when I was comparing w from ADCP and CTD dp/dt for some CTD-chipod stuff.

**Comment by andypicke** [comment]
Same bug in beam2earth.m  

Do we need beam2earth AND beam2earth_workhorse?

**Comment by sallywarner** [comment]
Andy, please fix these bugs. Let's keep both versions of the code. Thanks
